import type { Metadata } from "next";
import "./globals.css";
import { Tajawal } from "next/font/google";
import { Navbar } from "@/components/navbar";
import AutoStart from "@/components/auto-start";
import {Toaster} from "react-hot-toast"

const poppins = Tajawal({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
});


export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning dir="rtl" className="">
      <body
        className={`${poppins.className} dark:bg-gray-900 `}
      >
        <Toaster/>
        <AutoStart />
        <Navbar />
        {children}
        <div className="flex bg-gray-100 flex-col items-center py-6 justify-center">
          <p>© 2025 Behiry Tech. جميع الحقوق محفوظة.</p>
          <p className="app-version">الإصدار 1.0.0</p>
        </div>
      </body>
    </html>
  );
}
